import { error } from '@sveltejs/kit';
import { jellyfinUrl, authHeader } from '$lib/server/jellyfin.js';

// Streaming proxy between the browser and Jellyfin. This is the ONLY route
// through which media bytes flow. It is GET-only, requires a valid session
// (enforced in hooks.server.js), and only forwards whitelisted paths.
//
// Videos/* is matched by prefix rather than an exact endpoint list because the
// transcode playlist/segment URLs are generated by Jellyfin at runtime (and the
// v12 OpenAPI spec no longer documents them) — see docs/jellyfin-api.md.
const ALLOWED_PATHS = [
	/^videos\//i, // streams, HLS playlists + segments, subtitles, trickplay
	/^items\/[^/]+\/images\//i // posters, backdrops, thumbs
];

// Never forward auth material that might sit in a Jellyfin-generated URL.
const BLOCKED_PARAMS = new Set(['api_key', 'apikey', 'x-emby-token']);

const RESPONSE_HEADERS = [
	'content-type',
	'content-length',
	'content-range',
	'accept-ranges',
	'etag',
	'last-modified'
];

export async function GET({ params, url, request, locals }) {
	// hooks.server.js already rejects unauthenticated /api/ requests; this is defense in depth.
	if (!locals.session) error(401, 'Unauthorized');

	const path = params.path;
	if (!ALLOWED_PATHS.some((pattern) => pattern.test(path))) {
		error(403, 'Path not allowed');
	}

	const upstream = new URL(`${jellyfinUrl()}/${path}`);
	for (const [key, value] of url.searchParams) {
		if (!BLOCKED_PARAMS.has(key.toLowerCase())) upstream.searchParams.append(key, value);
	}

	const forwardHeaders = new Headers({
		Authorization: authHeader(locals.session.deviceId, locals.session.token)
	});
	for (const name of ['range', 'accept', 'if-none-match', 'if-modified-since']) {
		const value = request.headers.get(name);
		if (value) forwardHeaders.set(name, value);
	}

	const res = await fetch(upstream, { headers: forwardHeaders, signal: request.signal });

	const headers = new Headers();
	for (const name of RESPONSE_HEADERS) {
		const value = res.headers.get(name);
		if (value) headers.set(name, value);
	}
	const isImage = /^items\//i.test(path);
	headers.set('cache-control', isImage ? 'private, max-age=86400' : 'no-store');

	// HLS playlists may embed the Jellyfin token as api_key in segment URLs.
	// Rewrite the playlist text so it never reaches the browser; segment
	// requests are re-authenticated by this proxy via the header above.
	const contentType = res.headers.get('content-type') ?? '';
	if (path.endsWith('.m3u8') || contentType.includes('mpegurl')) {
		const text = (await res.text()).replace(/([?&])(api_key|ApiKey)=[^&\s"]*/g, '$1');
		headers.delete('content-length');
		headers.set('content-type', 'application/vnd.apple.mpegurl');
		return new Response(text, { status: res.status, headers });
	}

	return new Response(res.body, { status: res.status, headers });
}
